### ISSUE TITLE
Metrics from old pods not purged?

### ISSUE THREAD

**Issue by mcanevet** [jmcgrath207/k8s-ephemeral-storage-metrics#12]
Hello, I don't know if I did something wrong, but I get this pattern on a cluster with a lot of ephemeral pods (because it hosts gitlab jobs):
![image](https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/assets/2950673/f38111ad-bb49-4a61-a192-ac8988075e54)
It looks like it does not purge metrics from pods that does not exist anymore.

**Comment by jmcgrath207** [comment]
Thanks for bring this up @mcanevet 

Seems like we might need some filtering when scraping the k8 api on the surface here. I am going to have to research when k8s evicts dead pods from it's API query results.

A feature improvement we can make is adding pod labels to our exporter. I created a [issue](https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/issues/13) for it.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/main.go#L140


FWIW, I am current working on adding integration testing and hosted helm/images #4 . Hopefully I am done in the next few days and will start looking deeper into this.

If you find anything in the meantime let me know

**Comment by jmcgrath207** [comment]
@mcanevet  would a pod with init containers be a good test case for this?

**Comment by mcanevet** [comment]
@jmcgrath207 I'm not sure it's due to lack of filtering when scraping the k8s API because when I restart the exporter's pod, the count starts from 0 again, so I guess the API does not return the dead pods, otherwise we would have them even after a restart. My guess is that you continuously append to the same variable, which mean there is also a possible memory leak.

**Comment by jmcgrath207** [comment]
@mcanevet 

I just added some e2e tests for this and I believe the issue is fixed. It's on main now.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/actions/runs/6522694929
