### ISSUE TITLE
Scrape metrics for all nodes instead of current one

### ISSUE THREAD

**Issue by mcanevet** [jmcgrath207/k8s-ephemeral-storage-metrics#14]
IIUC, this project currently has to be deployed as a DaemonSet, because each pod will scrape only the metrics of the pods located on the same node. I guess we could technically have a single pod scraping all nodes's pods and hence deploy it as a Deployment which would reduce the number of pods required to monitor a cluster.

**Comment by jmcgrath207** [comment]
Agreed, we should have this feature. 

I won't get to it soon, but I'am open to PRs for this.

**Comment by jmcgrath207** [comment]
@mcanevet I've added this change and it's the default in the latest release.

Let me know how it goes :grin:
