### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by jmcgrath207** [jmcgrath207/k8s-ephemeral-storage-metrics#24]
Create a Grafana dashboard to be hosted here:
 
https://grafana.com/grafana/dashboards/

**Comment by mohsenkamini** [comment]
This is very important to get this exporter going and make use of it. @jmcgrath207 As you better than anyone know what this exporter provides, I think it would help if you provide what panels could be implemented within the dashboard to get someone started on this. You could also provide the queries needed for those panels.

**Comment by Cajga** [comment]
See this PR: https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/pull/125

**Comment by jmcgrath207** [comment]
Closing due to Merged PR https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/pull/125
