### ISSUE TITLE
v1.1.0 sometimes fails with: the server could not find the requested resource

### ISSUE THREAD

**Issue by mcanevet** [jmcgrath207/k8s-ephemeral-storage-metrics#31]
I have one this exporter installed on 3 clusters, and on only one of them it loop crashes with:
```
{"level":"info","time":1698151937,"message":"Starting server listening on :9100"}
{"level":"error","time":1698152254,"message":"ErrorBadRequst : the server could not find the requested resource\n"}
```

**Comment by jmcgrath207** [comment]
Weird, could you run it again but change the logs to debug and share that?

Also were these upgrades or fresh installs? Wondering if it didn't upgrade the role RBAC permissions to list nodes.

**Comment by mcanevet** [comment]
I can't really post the full logs because it contains a lot of informations regarding our internal applications names and I'm not sure that I'm allowed to show that, but basically it does something like that:

```
{"level":"debug","time":1698160268,"message":"Fetched proxy stats from node : XXXX"}
...
{"level":"debug","time":1698160269,"message":"Fetched proxy stats from node : XXXX"}
...
{"level":"debug","time":1698160269,"message":"pod argocd/argocd-redis-ha-server-1 on ... with usedBytes: 5431296.000000"}
{"level":"error","time":1698160269,"message":"ErrorBadRequst : the server could not find the requested resource\n"}
```

**Comment by jmcgrath207** [comment]
Gotcha, no worries.

What version of k8s are those three clusters running?

**Comment by mcanevet** [comment]
1.28.1 (it's an EKS).

**Comment by jmcgrath207** [comment]
@canidam added a fix that might have been your issue. Let me know how the `1.1.1` release works for you.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/issues/32

**Comment by mcanevet** [comment]
@jmcgrath207 still have the issue (although only on one cluster out of 3)

**Comment by jmcgrath207** [comment]
Looking deeper into it, seems to be caused by the API query not having a good back off/retry logic

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/main.go#L166.

I will add this and let you know when to retest.

**Comment by mcanevet** [comment]
I think I'll quickly see whether or not it fixes the problem on my setup.

**Comment by jmcgrath207** [comment]
Try out the new 1.2.0 release.

**Comment by mcanevet** [comment]
Rollout in progress. We should have the result soon because 1.1.0 restarted ~150 times within the last 24 hours...

**Comment by mcanevet** [comment]
5 hours without a single restart. I guess we're good.
Thank you!
