### ISSUE TITLE
When deploy_type is Deployment the app exit with unknown error

### ISSUE THREAD

**Issue by canidam** [jmcgrath207/k8s-ephemeral-storage-metrics#32]
When setting up DEPLOY_TYPE to "deployment", the app behaves unexpectedly (it thinks it's a daemonset) and exits with "ErrorBadRequest: unknown".

Now, I think it should either change the input to lower and compare against lower strings or if we expect to get exact string in exact case, validate that and exit with proper error.

Since the code expect Deployment or DaemonSet, I think the 2nd option fits here (it also correlates with K8s kinds).

**Comment by jmcgrath207** [comment]
Thanks @canidam, I will release this later today.
