### ISSUE TITLE
Add Arm image builds

### ISSUE THREAD

**Issue by jmcgrath207** [jmcgrath207/k8s-ephemeral-storage-metrics#39]

**Comment by matzegebbe** [comment]
Do you have the idea to provide ARM images or do you need help? https://github.com/docker/setup-buildx-action is suitable for this @jmcgrath207

**Comment by jmcgrath207** [comment]
Nope, haven't found the need yet.

So, I don't have a release pipeline. I build it locally with `make release`

If you want to add arm support, here is where I call those docker build scripts.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/main/scripts/release-docker.sh#L18-L28

Thanks!
