### ISSUE TITLE
Add ability to specify tolerations for deployment

### ISSUE THREAD

**Issue by trashadewan** [jmcgrath207/k8s-ephemeral-storage-metrics#51]
we  wish the deployment to run on certain  set of nodes always and other things not to run on them. It ll be helpful to allow for tolerations so we can set them along with node selectors to achieve this. 

Would be happy to raise a PR for it the edits in Helm Chart, if allowed.

**Comment by jmcgrath207** [comment]
Sounds Great! I welcome PR for this

**Comment by trashadewan** [comment]
Please review this PR:
https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/pull/52

**Comment by jmcgrath207** [comment]
Thanks, your change is live in the new 1.4.3
