### ISSUE TITLE
Pod crash on panic of interface conversation

### ISSUE THREAD

**Issue by canidam** [jmcgrath207/k8s-ephemeral-storage-metrics#9]
I've some pods that sometimes crash with the following panic.
This happens from time to time:

```
{"level":"info","time":1695111317,"message":"Starting server listening on :9100"}
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 10 [running]:
main.getMetrics()
	/code/main.go:112 +0x930
created by main.main
	/code/main.go:148 +0x76
```

Maybe worth validating the conversation of interfaces, and if it fails to be what the code expects it to log it as error but keep running?

**Comment by jmcgrath207** [comment]
Agree, we should break up this line for that functionality.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/main.go#L112C50-L112C50

For the log I am think dumping the `podName`, `podNamespace` should be sufficient. 

It's probably going to be a week until I can fix it, but I am happy to accept PRs.
